/**
 * Murf's voice catalogue, per model. GENERATED — do not hand-edit.
 *
 *   cd backend && npm run murf:voices
 *
 * Falcon 2 and Gen2 do not share a voice list: 137 and 163 voices with
 * 100 in common. Offering one model the other's voice is a hard
 * error from the vendor, which is why these lists hang off the model rather than
 * off the provider. Read from the live API on 2026-09-05.
 */

import type { ModelEntry } from './catalog.js';

export const MURF_FALCON_VOICES: ModelEntry[] = [
  { id: 'en-US-natalie', name: 'Natalie (F) · en-US', note: 'Conversation' },
  { id: 'en-US-alicia', name: 'Alicia (F) · en-US', note: 'Conversation' },
  { id: 'en-US-alina', name: 'Alina (F) · en-US', note: 'Conversation' },
  { id: 'en-US-amara', name: 'Amara (F) · en-US', note: 'Conversational' },
  { id: 'en-US-angela', name: 'Angela (F) · en-US', note: 'Promo' },
  { id: 'en-US-ariana', name: 'Ariana (F) · en-US', note: 'Conversation' },
  { id: 'en-US-caleb', name: 'Caleb (M) · en-US', note: 'Conversation' },
  { id: 'en-US-charles', name: 'Charles (M) · en-US', note: 'Conversation' },
  { id: 'en-US-cooper', name: 'Cooper (M) · en-US', note: 'Conversation' },
  { id: 'en-US-daisy', name: 'Daisy (F) · en-US', note: 'Conversation' },
  { id: 'en-US-daniel', name: 'Daniel (M) · en-US', note: 'Conversation' },
  { id: 'en-US-edmund', name: 'Edmund (M) · en-US', note: 'Conversation' },
  { id: 'en-US-ezekiel', name: 'Ezekiel (M) · en-US', note: 'Conversational' },
  { id: 'en-US-gordon', name: 'Gordon (M) · en-US', note: 'Conversational' },
  { id: 'en-US-grant', name: 'Grant (M) · en-US', note: 'Conversational' },
  { id: 'en-US-jayden', name: 'Jayden (M) · en-US', note: 'Conversation' },
  { id: 'en-US-josie', name: 'Josie (F) · en-US', note: 'Conversation' },
  { id: 'en-US-judith', name: 'Judith (F) · en-US', note: 'Conversational' },
  { id: 'en-US-luna', name: 'Luna (F) · en-US', note: 'Conversation' },
  { id: 'en-US-madison', name: 'Madison (F) · en-US', note: 'Conversational' },
  { id: 'en-US-matthew', name: 'Matthew (M) · en-US', note: 'Conversation' },
  { id: 'en-US-maverick', name: 'Maverick (M) · en-US', note: 'Conversation' },
  { id: 'en-US-michelle', name: 'Michelle (F) · en-US', note: 'Conversation' },
  { id: 'en-US-miles', name: 'Miles (M) · en-US', note: 'AIAgent / Customer Support Agent' },
  { id: 'en-US-molly', name: 'Molly (F) · en-US', note: 'Conversation' },
  { id: 'en-US-ronnie', name: 'Ronnie (M) · en-US', note: 'Conversation' },
  { id: 'en-US-wayne', name: 'Wayne (M) · en-US', note: 'Conversation' },
  { id: 'en-US-will', name: 'Will (M) · en-US', note: 'Conversation' },
  { id: 'en-IN-aarav', name: 'Aarav (M) · en-IN' },
  { id: 'en-IN-abhinav', name: 'Abhinav (M) · en-IN', note: 'Conversational · +3 locales' },
  { id: 'en-IN-alia', name: 'Alia (F) · en-IN' },
  { id: 'en-IN-anisha', name: 'Anisha (F) · en-IN', note: 'Conversation · +10 locales' },
  { id: 'en-IN-anusha', name: 'Anusha (F) · en-IN', note: 'Conversational · +4 locales' },
  { id: 'en-IN-arohi', name: 'Arohi (F) · en-IN' },
  { id: 'en-IN-eashwar', name: 'Eashwar (M) · en-IN' },
  { id: 'en-IN-isha', name: 'Isha (F) · en-IN' },
  { id: 'en-IN-nikhil', name: 'Nikhil (M) · en-IN', note: 'Conversational · +1 locales' },
  { id: 'en-IN-pooja', name: 'Pooja (F) · en-IN', note: 'Conversational · +6 locales' },
  { id: 'en-IN-priya', name: 'Priya (F) · en-IN', note: 'Conversational · +1 locales' },
  { id: 'en-IN-samar', name: 'Samar (M) · en-IN', note: 'Conversational · +7 locales' },
  { id: 'en-UK-benedict', name: 'Benedict (M) · en-UK', note: 'Conversational' },
  { id: 'en-UK-bertie', name: 'Bertie (M) · en-UK', note: 'Conversational · +1 locales' },
  { id: 'en-UK-freddie', name: 'Freddie (M) · en-UK', note: 'Conversational' },
  { id: 'en-UK-hazel', name: 'Hazel (F) · en-UK', note: 'Conversational' },
  { id: 'en-UK-heidi', name: 'Heidi (F) · en-UK', note: 'Conversational · +1 locales' },
  { id: 'en-UK-hugo', name: 'Hugo (M) · en-UK', note: 'Conversational' },
  { id: 'en-UK-joshua', name: 'Joshua (M) · en-UK', note: 'Conversational · +1 locales' },
  { id: 'en-UK-juliet', name: 'Juliet (F) · en-UK', note: 'Conversational' },
  { id: 'en-UK-lydia', name: 'Lydia (F) · en-UK', note: 'Conversational' },
  { id: 'en-UK-mason', name: 'Mason (M) · en-UK', note: 'Conversational' },
  { id: 'en-UK-pearl', name: 'Pearl (F) · en-UK', note: 'Conversational' },
  { id: 'en-UK-ruby', name: 'Ruby (F) · en-UK', note: 'Conversational' },
  { id: 'en-UK-sharon', name: 'Sharon (F) · en-UK', note: 'Conversational' },
  { id: 'en-UK-theo', name: 'Theo (M) · en-UK', note: 'Narration' },
  { id: 'en-AU-harper', name: 'Harper (M) · en-AU', note: 'Conversational' },
  { id: 'en-AU-ivy', name: 'Ivy (F) · en-AU', note: 'Conversational' },
  { id: 'en-AU-jimm', name: 'Jimm (M) · en-AU', note: 'Conversational' },
  { id: 'en-AU-leyton', name: 'Leyton (M) · en-AU', note: 'Conversational' },
  { id: 'en-AU-sophia', name: 'Sophia (F) · en-AU', note: 'Narration' },
  { id: 'hi-IN-aman', name: 'Aman (M) · hi-IN', note: 'Conversational' },
  { id: 'hi-IN-ayushi', name: 'Ayushi (F) · hi-IN', note: 'Conversation' },
  { id: 'hi-IN-karan', name: 'Karan (M) · hi-IN', note: 'Conversational · +1 locales' },
  { id: 'hi-IN-khyati', name: 'Khyati (F) · hi-IN', note: 'Conversational' },
  { id: 'hi-IN-namrita', name: 'Namrita (F) · hi-IN', note: 'Conversational · +2 locales' },
  { id: 'hi-IN-shweta', name: 'Shweta (F) · hi-IN', note: 'Conversational' },
  { id: 'hi-IN-sunaina', name: 'Sunaina (F) · hi-IN', note: 'Conversational · +1 locales' },
  { id: 'bn-IN-abhik', name: 'Abhik (M) · bn-IN' },
  { id: 'bn-IN-arnab', name: 'Arnab (M) · bn-IN' },
  { id: 'bn-IN-debarati', name: 'Debarati (F) · bn-IN', note: 'Conversational' },
  { id: 'bn-IN-ishani', name: 'Ishani (F) · bn-IN' },
  { id: 'bn-IN-subhankar', name: 'Subhankar (M) · bn-IN', note: 'Conversational · +1 locales' },
  { id: 'cs-CZ-antoninneuralczechtest', name: 'antoninNeuralCzechTest (M) · cs-CZ', note: 'Conversational' },
  { id: 'de-DE-björn', name: 'Björn (M) · de-DE', note: 'Conversational · +1 locales' },
  { id: 'de-DE-erna', name: 'Erna (F) · de-DE', note: 'Conversational' },
  { id: 'de-DE-lara', name: 'Lara (F) · de-DE', note: 'Conversational · +1 locales' },
  { id: 'de-DE-ralf', name: 'Ralf (M) · de-DE', note: 'Conversational · +1 locales' },
  { id: 'el-GR-stavros', name: 'Stavros (M) · el-GR', note: 'Narration' },
  { id: 'en-SCOTT-emily', name: 'Emily (F) · en-SCOTT', note: 'Conversational' },
  { id: 'en-SCOTT-rory', name: 'Rory (M) · en-SCOTT', note: 'Conversational' },
  { id: 'es-ES-carmen', name: 'Carmen (F) · es-ES', note: 'Conversational · +1 locales' },
  { id: 'es-ES-elvira', name: 'Elvira (F) · es-ES' },
  { id: 'es-ES-javier', name: 'Javier (M) · es-ES', note: 'Conversational' },
  { id: 'es-MX-carlos', name: 'Carlos (M) · es-MX', note: 'Conversational · +1 locales' },
  { id: 'es-MX-luisa', name: 'Luisa (F) · es-MX', note: 'Conversational' },
  { id: 'es-MX-valeria', name: 'Valeria (F) · es-MX', note: 'Conversational' },
  { id: 'fr-CA-alexis', name: 'Alexis (M) · fr-CA', note: 'Conversational · +1 locales' },
  { id: 'fr-CA-clément', name: 'Clément (M) · fr-CA', note: 'Conversational' },
  { id: 'fr-FR-adélie', name: 'Adélie (F) · fr-FR', note: 'Conversational' },
  { id: 'fr-FR-axel', name: 'Axel (M) · fr-FR', note: 'Conversational' },
  { id: 'fr-FR-guillaume', name: 'Guillaume (M) · fr-FR', note: 'Conversational' },
  { id: 'fr-FR-justine', name: 'Justine (F) · fr-FR', note: 'Conversational' },
  { id: 'gu-IN-diya', name: 'Diya (F) · gu-IN', note: 'Conversational · +3 locales' },
  { id: 'gu-IN-hardik', name: 'Hardik (M) · gu-IN', note: 'Conversational · +4 locales' },
  { id: 'hr-HR-marija', name: 'Marija (F) · hr-HR' },
  { id: 'it-IT-angelo', name: 'Angelo (M) · it-IT', note: 'Conversational' },
  { id: 'it-IT-giulia', name: 'Giulia (F) · it-IT' },
  { id: 'it-IT-greta', name: 'Greta (F) · it-IT', note: 'Conversational' },
  { id: 'it-IT-vera', name: 'Vera (F) · it-IT', note: 'Conversational' },
  { id: 'it-IT-vincenzo', name: 'Vincenzo (M) · it-IT', note: 'Conversational' },
  { id: 'ja-JP-denki', name: 'Denki (M) · ja-JP', note: 'Conversational' },
  { id: 'ja-JP-kenji', name: 'Kenji (M) · ja-JP', note: 'Conversational' },
  { id: 'ja-JP-kimi', name: 'Kimi (F) · ja-JP', note: 'Conversational' },
  { id: 'kn-IN-harshitha', name: 'Harshitha (F) · kn-IN', note: 'Conversational' },
  { id: 'ko-KR-jangmi', name: 'Jangmi (F) · ko-KR', note: 'Conversational' },
  { id: 'ko-KR-jong-su', name: 'Jong-su (M) · ko-KR', note: 'Conversational' },
  { id: 'ko-KR-seok', name: 'Seok (M) · ko-KR', note: 'Conversational' },
  { id: 'ml-IN-madhavan', name: 'Madhavan (M) · ml-IN', note: 'Conversational · +1 locales' },
  { id: 'ml-IN-nimisha', name: 'Nimisha (F) · ml-IN', note: 'Conversational · +1 locales' },
  { id: 'mr-IN-prajakta', name: 'Prajakta (F) · mr-IN', note: 'Conversational · +2 locales' },
  { id: 'mr-IN-prathamesh', name: 'Prathamesh (M) · mr-IN', note: 'Conversational · +2 locales' },
  { id: 'mr-IN-vaibhav', name: 'Vaibhav (M) · mr-IN', note: 'Conversational · +1 locales' },
  { id: 'nl-NL-dirk', name: 'Dirk (M) · nl-NL', note: 'Conversational · +1 locales' },
  { id: 'nl-NL-famke', name: 'Famke (F) · nl-NL', note: 'Conversational' },
  { id: 'nl-NL-merel', name: 'Merel (F) · nl-NL', note: 'Conversational · +1 locales' },
  { id: 'pa-IN-harman', name: 'Harman (M) · pa-IN', note: 'Conversational' },
  { id: 'pa-IN-harpreet', name: 'Harpreet (F) · pa-IN', note: 'Conversational · +2 locales' },
  { id: 'pl-PL-blazej', name: 'Blazej (M) · pl-PL', note: 'Conversational · +1 locales' },
  { id: 'pl-PL-jacek', name: 'Jacek (M) · pl-PL', note: 'Conversational' },
  { id: 'pl-PL-kasia', name: 'Kasia (F) · pl-PL', note: 'Conversational' },
  { id: 'pt-BR-benício', name: 'Benício (M) · pt-BR', note: 'Conversational' },
  { id: 'pt-BR-eloa', name: 'Eloa (F) · pt-BR', note: 'Conversational' },
  { id: 'pt-BR-gustavo', name: 'Gustavo (M) · pt-BR', note: 'Conversational' },
  { id: 'pt-BR-heitor', name: 'Heitor (M) · pt-BR', note: 'Conversational · +1 locales' },
  { id: 'pt-BR-isadora', name: 'Isadora (F) · pt-BR', note: 'Conversational · +1 locales' },
  { id: 'pt-BR-silvio', name: 'Silvio (M) · pt-BR', note: 'Conversational' },
  { id: 'pt-BR-yago', name: 'Yago (M) · pt-BR', note: 'Conversational' },
  { id: 'sk-SK-nina', name: 'Nina (F) · sk-SK', note: 'Conversational' },
  { id: 'sk-SK-tibor', name: 'Tibor (M) · sk-SK', note: 'Conversational' },
  { id: 'ta-IN-abirami', name: 'Abirami (F) · ta-IN', note: '+1 locales' },
  { id: 'ta-IN-iniya', name: 'Iniya (F) · ta-IN' },
  { id: 'ta-IN-karthikeyan', name: 'Karthikeyan (M) · ta-IN', note: 'Conversational · +1 locales' },
  { id: 'ta-IN-sarvesh', name: 'Sarvesh (M) · ta-IN' },
  { id: 'tl-PH-eraño', name: 'Eraño (M) · tl-PH', note: 'Conversational' },
  { id: 'zh-CN-jiao', name: 'Jiao (F) · zh-CN', note: 'Conversational · +1 locales' },
  { id: 'zh-CN-tao', name: 'Tao (M) · zh-CN', note: 'Conversational' },
  { id: 'zh-CN-wei', name: 'Wei (F) · zh-CN', note: 'Conversational' },
  { id: 'zh-CN-yuxan', name: 'Yuxan (M) · zh-CN', note: 'Conversational' },
];

export const MURF_FALCON_LOCALES: ModelEntry[] = [
  { id: 'en-US', name: 'English (US & Canada) (en-US)' },
  { id: 'en-IN', name: 'English (India) (en-IN)' },
  { id: 'en-UK', name: 'English (UK) (en-UK)' },
  { id: 'en-AU', name: 'English (Australia) (en-AU)' },
  { id: 'hi-IN', name: 'Hindi (India) (hi-IN)' },
  { id: 'as-IN', name: 'Assamese (India) (as-IN)' },
  { id: 'bn-IN', name: 'Bangla (bn-IN)' },
  { id: 'cs-CZ', name: 'Czech (Czech Republic) (cs-CZ)' },
  { id: 'de-DE', name: 'German (Germany) (de-DE)' },
  { id: 'el-GR', name: 'Greek (Greece) (el-GR)' },
  { id: 'en-SCOTT', name: 'English (Scotland) (en-SCOTT)' },
  { id: 'es-ES', name: 'Spanish (es-ES)' },
  { id: 'es-MX', name: 'Spanish (Mexico) (es-MX)' },
  { id: 'fr-CA', name: 'French (Canada) (fr-CA)' },
  { id: 'fr-FR', name: 'French (France) (fr-FR)' },
  { id: 'gu-IN', name: 'Gujarati (India) (gu-IN)' },
  { id: 'hi-LATN', name: 'Hinglish (India) (hi-LATN)' },
  { id: 'hr-HR', name: 'Croatian (hr-HR)' },
  { id: 'it-IT', name: 'Italian (Italy) (it-IT)' },
  { id: 'ja-JP', name: 'Japanese (Japan) (ja-JP)' },
  { id: 'kn-IN', name: 'Kannada (India) (kn-IN)' },
  { id: 'ko-KR', name: 'Korean (South Korea) (ko-KR)' },
  { id: 'ml-IN', name: 'Malayalam (India) (ml-IN)' },
  { id: 'mr-IN', name: 'Marathi (India) (mr-IN)' },
  { id: 'nl-NL', name: 'Dutch (Netherlands) (nl-NL)' },
  { id: 'or-IN', name: 'Odia (India) (or-IN)' },
  { id: 'pa-IN', name: 'Punjabi (India) (pa-IN)' },
  { id: 'pl-PL', name: 'Polish (Poland) (pl-PL)' },
  { id: 'pt-BR', name: 'Portuguese (Brazil) (pt-BR)' },
  { id: 'sk-SK', name: 'Slovak (Slovakia) (sk-SK)' },
  { id: 'ta-IN', name: 'Tamil (India) (ta-IN)' },
  { id: 'te-IN', name: 'Telugu (India) (te-IN)' },
  { id: 'tl-PH', name: 'Tagalog (Philippines) (tl-PH)' },
  { id: 'tr-TR', name: 'Turkish (Turkey) (tr-TR)' },
  { id: 'vi-VN', name: 'Vietnamese (Vietnam) (vi-VN)' },
  { id: 'zh-CN', name: 'Mandarin (China) (zh-CN)' },
];

export const MURF_GEN2_VOICES: ModelEntry[] = [
  { id: 'en-US-natalie', name: 'Natalie (F) · en-US', note: 'Angry / Conversational / Furious · +40 locales' },
  { id: 'en-US-abigail', name: 'Abigail (F) · en-US', note: 'Conversational / Narration' },
  { id: 'en-US-alicia', name: 'Alicia (F) · en-US', note: 'Angry / Calm / Conversational · +3 locales' },
  { id: 'en-US-alina', name: 'Alina (F) · en-US', note: 'Conversational' },
  { id: 'en-US-amara', name: 'Amara (F) · en-US', note: 'Conversational / Narration · +40 locales' },
  { id: 'en-US-angela', name: 'Angela (F) · en-US', note: 'Promo' },
  { id: 'en-US-ariana', name: 'Ariana (F) · en-US', note: 'Conversational / Conversational / Narration' },
  { id: 'en-US-caleb', name: 'Caleb (M) · en-US', note: 'Conversational / Promo' },
  { id: 'en-US-carter', name: 'Carter (M) · en-US', note: 'Calm / Conversational / Documentary · +40 locales' },
  { id: 'en-US-charles', name: 'Charles (M) · en-US', note: 'Angry / Calm / Conversational · +6 locales' },
  { id: 'en-US-charlotte', name: 'Charlotte (F) · en-US', note: 'Narration' },
  { id: 'en-US-claire', name: 'Claire (F) · en-US', note: 'Luxury / Narration' },
  { id: 'en-US-cooper', name: 'Cooper (M) · en-US', note: 'Angry / Conversational / Inspirational' },
  { id: 'en-US-daisy', name: 'Daisy (F) · en-US', note: 'Conversational / Narration / NewsCast' },
  { id: 'en-US-daniel', name: 'Daniel (M) · en-US', note: 'Conversational / Inspirational / Sad' },
  { id: 'en-US-delilah', name: 'Delilah (F) · en-US', note: 'Conversational / Narration' },
  { id: 'en-US-denzel', name: 'Denzel (M) · en-US', note: 'Conversational / Promo' },
  { id: 'en-US-dylan', name: 'Dylan (M) · en-US', note: 'Conversational / Documentary / Inspirational' },
  { id: 'en-US-edmund', name: 'Edmund (M) · en-US', note: 'Conversational / Inspirational / NewsCast' },
  { id: 'en-US-evander', name: 'Evander (M) · en-US', note: 'Conversational / Friendly / Narration' },
  { id: 'en-US-imani', name: 'Imani (F) · en-US', note: 'Conversational' },
  { id: 'en-US-iris', name: 'Iris (F) · en-US', note: 'Conversational / Friendly / Narration' },
  { id: 'en-US-jayden', name: 'Jayden (M) · en-US', note: 'Conversational / Friendly / Narration' },
  { id: 'en-US-josie', name: 'Josie (F) · en-US', note: 'Conversational / Narration' },
  { id: 'en-US-julia', name: 'Julia (F) · en-US', note: 'Angry / Calm / Conversational' },
  { id: 'en-US-june', name: 'June (F) · en-US', note: 'Promo' },
  { id: 'en-US-ken', name: 'Ken (M) · en-US', note: 'Angry / Audiobook / Calm · +40 locales' },
  { id: 'en-US-lucas', name: 'Lucas (M) · en-US', note: 'Promo' },
  { id: 'en-US-marcus', name: 'Marcus (M) · en-US', note: 'Conversational / Narration' },
  { id: 'en-US-maverick', name: 'Maverick (M) · en-US', note: 'Narration · +40 locales' },
  { id: 'en-US-michelle', name: 'Michelle (F) · en-US', note: 'Conversational · +3 locales' },
  { id: 'en-US-miles', name: 'Miles (M) · en-US', note: 'Angry / Calm / Conversational · +40 locales' },
  { id: 'en-US-molly', name: 'Molly (F) · en-US', note: 'Conversational' },
  { id: 'en-US-naomi', name: 'Naomi (F) · en-US', note: 'Conversational / Inspirational · +1 locales' },
  { id: 'en-US-paul', name: 'Paul (M) · en-US', note: 'Audiobook / Conversational / Narration' },
  { id: 'en-US-phoebe', name: 'Phoebe (F) · en-US', note: 'Conversational · +2 locales' },
  { id: 'en-US-riley', name: 'Riley (F) · en-US', note: 'Narration / Promo · +2 locales' },
  { id: 'en-US-river', name: 'River (NB) · en-US', note: 'Conversational' },
  { id: 'en-US-ronnie', name: 'Ronnie (M) · en-US', note: 'Conversational / NewsCast / Promo · +4 locales' },
  { id: 'en-US-ryan', name: 'Ryan (M) · en-US', note: 'Angry / Conversational / Narration' },
  { id: 'en-US-samantha', name: 'Samantha (F) · en-US', note: 'Angry / Conversational / Luxury · +40 locales' },
  { id: 'en-US-terrell', name: 'Terrell (M) · en-US', note: 'Calm / Conversational / Inspirational · +3 locales' },
  { id: 'en-US-wayne', name: 'Wayne (M) · en-US', note: 'Angry / Calm / Conversational · +40 locales' },
  { id: 'en-US-zion', name: 'Zion (M) · en-US', note: 'Conversational / Narration / Promo' },
  { id: 'en-IN-aarav', name: 'Aarav (M) · en-IN', note: 'Conversational' },
  { id: 'en-IN-alia', name: 'Alia (F) · en-IN', note: 'Documentary / Narration / Promo' },
  { id: 'en-IN-arohi', name: 'Arohi (F) · en-IN', note: 'Conversational / Promo' },
  { id: 'en-IN-eashwar', name: 'Eashwar (M) · en-IN', note: 'Conversational / Narration' },
  { id: 'en-IN-isha', name: 'Isha (F) · en-IN', note: 'Conversational / Narration' },
  { id: 'en-IN-priya', name: 'Priya (F) · en-IN', note: 'Conversational / Narration / Promo' },
  { id: 'en-IN-rohan', name: 'Rohan (M) · en-IN', note: 'Conversational / Narration / Promo' },
  { id: 'en-UK-aiden', name: 'Aiden (M) · en-UK', note: 'Character / Conversational / Narration' },
  { id: 'en-UK-amber', name: 'Amber (F) · en-UK', note: 'Conversational / Documentary' },
  { id: 'en-UK-finley', name: 'Finley (M) · en-UK', note: 'Angry / Conversational / Narration' },
  { id: 'en-UK-freddie', name: 'Freddie (M) · en-UK', note: 'Conversational / Narration · +40 locales' },
  { id: 'en-UK-gabriel', name: 'Gabriel (M) · en-UK', note: 'Documentary / Evil / Promo · +3 locales' },
  { id: 'en-UK-harrison', name: 'Harrison (M) · en-UK', note: 'Conversational / Narration · +1 locales' },
  { id: 'en-UK-hazel', name: 'Hazel (F) · en-UK', note: 'Conversational · +40 locales' },
  { id: 'en-UK-heidi', name: 'Heidi (F) · en-UK', note: 'Conversational' },
  { id: 'en-UK-hugo', name: 'Hugo (M) · en-UK', note: 'Conversational · +1 locales' },
  { id: 'en-UK-jaxon', name: 'Jaxon (M) · en-UK', note: 'Conversational / Narration · +1 locales' },
  { id: 'en-UK-juliet', name: 'Juliet (F) · en-UK', note: 'Conversational / Narration · +40 locales' },
  { id: 'en-UK-katie', name: 'Katie (F) · en-UK', note: 'Conversational · +1 locales' },
  { id: 'en-UK-mason', name: 'Mason (M) · en-UK', note: 'Conversational' },
  { id: 'en-UK-pearl', name: 'Pearl (F) · en-UK', note: 'Conversational · +1 locales' },
  { id: 'en-UK-peter', name: 'Peter (M) · en-UK', note: 'Conversational / Narration · +40 locales' },
  { id: 'en-UK-reggie', name: 'Reggie (M) · en-UK', note: 'Promo' },
  { id: 'en-UK-ruby', name: 'Ruby (F) · en-UK', note: 'Angry / Calm / Conversational · +40 locales' },
  { id: 'en-UK-theo', name: 'Theo (M) · en-UK', note: 'Angry / Calm / Character · +18 locales' },
  { id: 'en-AU-ashton', name: 'Ashton (M) · en-AU', note: 'Narration / Promo' },
  { id: 'en-AU-evelyn', name: 'Evelyn (F) · en-AU', note: 'Conversational · +5 locales' },
  { id: 'en-AU-harper', name: 'Harper (M) · en-AU', note: 'Casual / Conversational' },
  { id: 'en-AU-ivy', name: 'Ivy (F) · en-AU', note: 'Angry / Calm / Conversational · +40 locales' },
  { id: 'en-AU-jimm', name: 'Jimm (M) · en-AU', note: 'Conversational / Narration · +5 locales' },
  { id: 'en-AU-joyce', name: 'Joyce (F) · en-AU', note: 'Conversational / Narration' },
  { id: 'en-AU-kylie', name: 'Kylie (F) · en-AU', note: 'Calm / Conversational · +40 locales' },
  { id: 'en-AU-leyton', name: 'Leyton (M) · en-AU', note: 'Angry / Calm / Conversational · +40 locales' },
  { id: 'en-AU-mitch', name: 'Mitch (M) · en-AU', note: 'Casual / Conversational / Narration · +40 locales' },
  { id: 'en-AU-shane', name: 'Shane (M) · en-AU', note: 'Conversational / Narration' },
  { id: 'en-AU-sophia', name: 'Sophia (F) · en-AU', note: 'Conversational / Narration' },
  { id: 'hi-IN-amit', name: 'Amit (M) · hi-IN', note: 'Conversational' },
  { id: 'hi-IN-ayushi', name: 'Ayushi (F) · hi-IN', note: 'Conversational' },
  { id: 'hi-IN-kabir', name: 'Kabir (M) · hi-IN', note: 'Conversational' },
  { id: 'hi-IN-rahul', name: 'Rahul (M) · hi-IN', note: 'Conversational' },
  { id: 'hi-IN-shaan', name: 'Shaan (M) · hi-IN', note: 'Calm / Conversational / Promo' },
  { id: 'hi-IN-shweta', name: 'Shweta (F) · hi-IN', note: 'Calm / Conversational / Promo' },
  { id: 'bn-IN-abhik', name: 'Abhik (M) · bn-IN', note: 'Conversational · +1 locales' },
  { id: 'bn-IN-anwesha', name: 'Anwesha (F) · bn-IN', note: 'Conversational · +40 locales' },
  { id: 'bn-IN-arnab', name: 'Arnab (M) · bn-IN', note: 'Conversational · +1 locales' },
  { id: 'bn-IN-ishani', name: 'Ishani (F) · bn-IN', note: 'Conversational · +1 locales' },
  { id: 'cs-CZ-antoninneuralczechtest', name: 'antoninNeuralCzechTest (M) · cs-CZ', note: 'General' },
  { id: 'de-DE-björn', name: 'Björn (M) · de-DE', note: 'Conversational / Promo · +1 locales' },
  { id: 'de-DE-erna', name: 'Erna (F) · de-DE', note: 'Conversational' },
  { id: 'de-DE-josephine', name: 'Josephine (F) · de-DE', note: 'Calm / Conversational / Promo · +40 locales' },
  { id: 'de-DE-lara', name: 'Lara (F) · de-DE', note: 'Conversational' },
  { id: 'de-DE-lia', name: 'Lia (F) · de-DE', note: 'Conversational' },
  { id: 'de-DE-matthias', name: 'Matthias (M) · de-DE', note: 'Angry / Calm / Conversational · +1 locales' },
  { id: 'de-DE-ralf', name: 'Ralf (M) · de-DE', note: 'Conversational' },
  { id: 'el-GR-stavros', name: 'Stavros (M) · el-GR', note: 'Narration · +40 locales' },
  { id: 'en-SCOTT-emily', name: 'Emily (F) · en-SCOTT', note: 'Conversational · +40 locales' },
  { id: 'en-SCOTT-rory', name: 'Rory (M) · en-SCOTT', note: 'Conversational' },
  { id: 'es-ES-carla', name: 'Carla (F) · es-ES', note: 'Conversational · +1 locales' },
  { id: 'es-ES-carmen', name: 'Carmen (F) · es-ES', note: 'Conversational' },
  { id: 'es-ES-elvira', name: 'Elvira (F) · es-ES', note: 'Conversational / Promo · +1 locales' },
  { id: 'es-ES-enrique', name: 'Enrique (M) · es-ES', note: 'Calm / Conversational / Promo' },
  { id: 'es-ES-javier', name: 'Javier (M) · es-ES', note: 'Conversational' },
  { id: 'es-MX-alejandro', name: 'Alejandro (M) · es-MX', note: 'Calm / Sad / Conversational' },
  { id: 'es-MX-carlos', name: 'Carlos (M) · es-MX', note: 'Conversational' },
  { id: 'es-MX-luisa', name: 'Luisa (F) · es-MX', note: 'Calm / Conversational / Promo' },
  { id: 'es-MX-valeria', name: 'Valeria (F) · es-MX', note: 'Conversational' },
  { id: 'fr-CA-alexis', name: 'Alexis (M) · fr-CA', note: 'Conversational' },
  { id: 'fr-CA-clément', name: 'Clément (M) · fr-CA', note: 'Conversational' },
  { id: 'fr-FR-adélie', name: 'Adélie (F) · fr-FR', note: 'Calm / Conversational / Promo · +40 locales' },
  { id: 'fr-FR-axel', name: 'Axel (M) · fr-FR', note: 'Conversational · +1 locales' },
  { id: 'fr-FR-guillaume', name: 'Guillaume (M) · fr-FR', note: 'Conversational' },
  { id: 'fr-FR-justine', name: 'Justine (F) · fr-FR', note: 'Angry / Calm / Conversational · +40 locales' },
  { id: 'fr-FR-louis', name: 'Louis (M) · fr-FR', note: 'Conversational / Promo · +40 locales' },
  { id: 'fr-FR-louise', name: 'Louise (F) · fr-FR', note: 'Conversational · +40 locales' },
  { id: 'fr-FR-maxime', name: 'Maxime (M) · fr-FR', note: 'Conversational' },
  { id: 'hr-HR-marija', name: 'Marija (F) · hr-HR', note: 'Narration · +40 locales' },
  { id: 'it-IT-angelo', name: 'Angelo (M) · it-IT', note: 'Conversational' },
  { id: 'it-IT-giorgio', name: 'Giorgio (M) · it-IT', note: 'Conversational · +1 locales' },
  { id: 'it-IT-giulia', name: 'Giulia (F) · it-IT', note: 'Conversational' },
  { id: 'it-IT-greta', name: 'Greta (F) · it-IT', note: 'Conversational · +1 locales' },
  { id: 'it-IT-lorenzo', name: 'Lorenzo (M) · it-IT', note: 'Conversational / Promo · +40 locales' },
  { id: 'it-IT-vera', name: 'Vera (F) · it-IT', note: 'Conversational' },
  { id: 'it-IT-vincenzo', name: 'Vincenzo (M) · it-IT', note: 'Conversational' },
  { id: 'ja-JP-denki', name: 'Denki (M) · ja-JP', note: 'Conversational' },
  { id: 'ja-JP-kenji', name: 'Kenji (M) · ja-JP', note: 'Conversational' },
  { id: 'ja-JP-kimi', name: 'Kimi (F) · ja-JP', note: 'Conversational' },
  { id: 'ko-KR-gyeong', name: 'Gyeong (F) · ko-KR', note: 'Conversational' },
  { id: 'ko-KR-hwan', name: 'Hwan (M) · ko-KR', note: 'Calm / Conversational / Promo' },
  { id: 'ko-KR-jangmi', name: 'Jangmi (F) · ko-KR', note: 'Conversational' },
  { id: 'ko-KR-jong-su', name: 'Jong-su (M) · ko-KR', note: 'Conversational' },
  { id: 'ko-KR-minseo', name: 'Minseo (F) · ko-KR', note: 'Conversational' },
  { id: 'ko-KR-sanghoon', name: 'SangHoon (M) · ko-KR', note: 'Conversational / Promo' },
  { id: 'ko-KR-seok', name: 'Seok (M) · ko-KR', note: 'Audiobook' },
  { id: 'nl-NL-dirk', name: 'Dirk (M) · nl-NL', note: 'Conversational · +40 locales' },
  { id: 'nl-NL-famke', name: 'Famke (F) · nl-NL', note: 'Conversational' },
  { id: 'nl-NL-merel', name: 'Merel (F) · nl-NL', note: 'Conversational' },
  { id: 'pl-PL-blazej', name: 'Blazej (M) · pl-PL', note: 'Conversational · +1 locales' },
  { id: 'pl-PL-jacek', name: 'Jacek (M) · pl-PL', note: 'Conversational · +40 locales' },
  { id: 'pl-PL-kasia', name: 'Kasia (F) · pl-PL', note: 'Conversational' },
  { id: 'pt-BR-benício', name: 'Benício (M) · pt-BR', note: 'Conversational · +1 locales' },
  { id: 'pt-BR-eloa', name: 'Eloa (F) · pt-BR', note: 'Conversational / Promo' },
  { id: 'pt-BR-gustavo', name: 'Gustavo (M) · pt-BR', note: 'Conversational' },
  { id: 'pt-BR-heitor', name: 'Heitor (M) · pt-BR', note: 'Conversational / Promo · +40 locales' },
  { id: 'pt-BR-isadora', name: 'Isadora (F) · pt-BR', note: 'Conversational · +40 locales' },
  { id: 'pt-BR-silvio', name: 'Silvio (M) · pt-BR', note: 'Conversational' },
  { id: 'pt-BR-yago', name: 'Yago (M) · pt-BR', note: 'Conversational' },
  { id: 'sk-SK-nina', name: 'Nina (F) · sk-SK', note: 'Narration' },
  { id: 'sk-SK-tibor', name: 'Tibor (M) · sk-SK', note: 'Narration' },
  { id: 'ta-IN-abirami', name: 'Abirami (F) · ta-IN', note: 'Conversational' },
  { id: 'ta-IN-iniya', name: 'Iniya (F) · ta-IN', note: 'Conversational · +40 locales' },
  { id: 'ta-IN-sarvesh', name: 'Sarvesh (M) · ta-IN', note: 'Conversational' },
  { id: 'ta-IN-suresh', name: 'Suresh (M) · ta-IN', note: 'Conversational · +1 locales' },
  { id: 'tl-PH-eraño', name: 'Eraño (M) · tl-PH', note: 'Conversational' },
  { id: 'zh-CN-baolin', name: 'Baolin (F) · zh-CN', note: 'Conversational / Promo / Sad' },
  { id: 'zh-CN-jiao', name: 'Jiao (F) · zh-CN', note: 'Conversational' },
  { id: 'zh-CN-tao', name: 'Tao (M) · zh-CN', note: 'Calm / Conversational / Promo' },
  { id: 'zh-CN-wei', name: 'Wei (F) · zh-CN', note: 'Calm / Conversational / Promo' },
  { id: 'zh-CN-yuxan', name: 'Yuxan (M) · zh-CN', note: 'Conversational' },
  { id: 'zh-CN-zhang', name: 'Zhang (M) · zh-CN', note: 'Calm / Conversational / Promo' },
];

export const MURF_GEN2_LOCALES: ModelEntry[] = [
  { id: 'en-US', name: 'English (US & Canada) (en-US)' },
  { id: 'en-IN', name: 'English (India) (en-IN)' },
  { id: 'en-UK', name: 'English (UK) (en-UK)' },
  { id: 'en-AU', name: 'English (Australia) (en-AU)' },
  { id: 'hi-IN', name: 'Hindi (India) (hi-IN)' },
  { id: 'bg-BG', name: 'Bulgarian (Bulgaria) (bg-BG)' },
  { id: 'bn-IN', name: 'Bangla (India) (bn-IN)' },
  { id: 'cs-CZ', name: 'Czech (Czech Republic) (cs-CZ)' },
  { id: 'de-DE', name: 'German (Germany) (de-DE)' },
  { id: 'el-GR', name: 'Greek (Greece) (el-GR)' },
  { id: 'en-SCOTT', name: 'English (Scotland) (en-SCOTT)' },
  { id: 'es-ES', name: 'Spanish (Spain) (es-ES)' },
  { id: 'es-MX', name: 'Spanish (Mexico) (es-MX)' },
  { id: 'fi-FI', name: 'Finnish (Finland) (fi-FI)' },
  { id: 'fr-CA', name: 'French (Canada) (fr-CA)' },
  { id: 'fr-FR', name: 'French (France) (fr-FR)' },
  { id: 'gu-IN', name: 'Gujarati (India) (gu-IN)' },
  { id: 'hr-HR', name: 'Croatian (Croatia) (hr-HR)' },
  { id: 'id-ID', name: 'Indonesian (Indonesia) (id-ID)' },
  { id: 'it-IT', name: 'Italian (Italy) (it-IT)' },
  { id: 'ja-JP', name: 'Japanese (Japan) (ja-JP)' },
  { id: 'kn-IN', name: 'Kannada (India) (kn-IN)' },
  { id: 'ko-KR', name: 'Korean (South Korea) (ko-KR)' },
  { id: 'ml-IN', name: 'Malayalam (India) (ml-IN)' },
  { id: 'mr-IN', name: 'Marathi (India) (mr-IN)' },
  { id: 'ms-MY', name: 'Malay (Malaysia) (ms-MY)' },
  { id: 'nl-BE', name: 'Dutch (Belgium) (nl-BE)' },
  { id: 'nl-NL', name: 'Dutch (Netherlands) (nl-NL)' },
  { id: 'pa-IN', name: 'Punjabi (India) (pa-IN)' },
  { id: 'pl-PL', name: 'Polish (Poland) (pl-PL)' },
  { id: 'pt-BR', name: 'Portuguese (Brazil) (pt-BR)' },
  { id: 'ro-RO', name: 'Romanian (Romania) (ro-RO)' },
  { id: 'sk-SK', name: 'Slovak (Slovakia) (sk-SK)' },
  { id: 'sv-SE', name: 'Swedish (Sweden) (sv-SE)' },
  { id: 'ta-IN', name: 'Tamil (India) (ta-IN)' },
  { id: 'te-IN', name: 'Telugu (India) (te-IN)' },
  { id: 'th-TH', name: 'Thai (Thailand) (th-TH)' },
  { id: 'tl-PH', name: 'Tagalog (Philippines) (tl-PH)' },
  { id: 'tr-TR', name: 'Turkish (Turkey) (tr-TR)' },
  { id: 'vi-VN', name: 'Vietnamese (Vietnam) (vi-VN)' },
  { id: 'zh-CN', name: 'Mandarin (China) (zh-CN)' },
];
